<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use App\Models\Notice;
use App\Services\NotificationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NoticeController extends Controller
{
    public function index()
    {
        $notices = Notice::with('creator')->orderBy('created_at', 'desc')->paginate(15);
        return view('settings.notices.index', compact('notices'));
    }


    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string|max:1000',
            'type' => 'required|in:notice,event',
            'expires_at' => 'nullable|date',
        ]);

        $validated['created_by'] = Auth::id();
        $validated['is_active'] = $request->has('is_active');

        $notice = Notice::create($validated);

        // Notify all active employees about the new notice/event
        $typeLabel = ucfirst($validated['type']);
        NotificationService::notifyAllEmployees(
            'notice',
            'New ' . $typeLabel . ': ' . \Illuminate\Support\Str::limit($notice->title, 30),
            \Illuminate\Support\Str::limit($notice->content, 80),
            route('employee-dashboard'),
            $notice
        );

        return redirect()->route('settings.notices.index')
            ->with('success', 'Notice/Event created successfully.');
    }


    public function update(Request $request, Notice $notice)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string|max:1000',
            'type' => 'required|in:notice,event',
            'expires_at' => 'nullable|date',
        ]);

        $validated['is_active'] = $request->has('is_active');

        $notice->update($validated);

        return redirect()->route('settings.notices.index')
            ->with('success', 'Notice/Event updated successfully.');
    }

    public function destroy(Notice $notice)
    {
        // Delete all notifications that were generated by this notice
        \App\Models\Notification::where('source_type', Notice::class)
            ->where('source_id', $notice->id)
            ->delete();

        $notice->delete();
        return redirect()->route('settings.notices.index')
            ->with('success', 'Notice/Event deleted successfully.');
    }
}
