$files = Get-ChildItem -Path "resources/views" -Filter "*.blade.php" -Recurse
foreach ($file in $files) {
    $content = Get-Content $file.FullName -Raw
    $content = $content -replace 'hr-panel-title', 'ui-panel-title'
    $content = $content -replace 'emp-panel-title', 'ui-panel-title'
    $content = $content -replace 'hr-metric-icon', 'ui-metric-icon'
    $content = $content -replace 'emp-metric-icon', 'ui-metric-icon'
    $content = $content -replace 'hr-metric-value', 'ui-metric-value'
    $content = $content -replace 'emp-metric-value', 'ui-metric-value'
    $content = $content -replace 'hr-metric-label', 'ui-metric-label'
    $content = $content -replace 'emp-metric-label', 'ui-metric-label'
    $content = $content -replace 'hr-sidebar-link', 'ui-sidebar-link'
    $content = $content -replace 'emp-sidebar-link', 'ui-sidebar-link'
    $content = $content -replace 'hr-sidebar-nav', 'ui-sidebar-nav'
    $content = $content -replace 'emp-sidebar-nav', 'ui-sidebar-nav'
    $content = $content -replace 'hr-sidebar-parent', 'ui-sidebar-parent'
    $content = $content -replace 'emp-sidebar-parent', 'ui-sidebar-parent'
    $content = $content -replace 'hr-sidebar-toggle', 'ui-sidebar-toggle'
    $content = $content -replace 'emp-sidebar-toggle', 'ui-sidebar-toggle'
    $content = $content -replace 'hr-sidebar-submenu', 'ui-sidebar-submenu'
    $content = $content -replace 'emp-sidebar-submenu', 'ui-sidebar-submenu'
    $content = $content -replace 'hr-chevron', 'ui-chevron'
    $content = $content -replace 'emp-chevron', 'ui-chevron'
    $content = $content -replace 'hr-main', 'ui-main'
    $content = $content -replace 'emp-main', 'ui-main'
    $content = $content -replace 'hr-layout', 'ui-layout'
    $content = $content -replace 'emp-layout', 'ui-layout'
    $content = $content -replace 'sidebar-overlay', 'ui-overlay'
    $content = $content -replace 'emp-sidebar-overlay', 'ui-overlay'
    $content = $content -replace 'mobile-topbar', 'ui-mobile-topbar'
    $content = $content -replace 'emp-mobile-topbar', 'ui-mobile-topbar'
    $content = $content -replace 'mobile-hamburger', 'ui-mobile-hamburger'
    $content = $content -replace 'topbar-brand', 'ui-topbar-brand'
    $content | Set-Content $file.FullName
}
